### PR TITLE
Add a utility method to create a new empty module

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
Looks like I've prematurely pushed this one again...

**Comment by andreaTP** [comment]
No worries, let me convert this to draft.

**Comment by dmlloyd** [comment]
This is ready now. But, I'm not sure it's really important anymore given the changes to how sections are parsed.

**Review by andreaTP — APPROVED** [review]
It's fine by me, you know that I would lock down the mutability a bit more in the future, but this is ok with the current tradeoffs and understanding.

**Comment by dmlloyd** [comment]
I'm going to close this one. I thought it might be useful for parsing, but in the end it turns out it's better to create the sections as we go than it is to pre-create them and populate them after the fact. I suspect that it will be the same for other use cases as well.

**Pull request closed without merging**
