### PR TITLE
Format code with Palantir Java Format

### PR DESCRIPTION
**Pull request by electrum**
This is a proposal to use [Palantir Java Format](https://github.com/palantir/palantir-java-format). It's based on `google-java-format` but is more lambda friendly. See the examples in the README and compare the formatted code. This resolves my personal complaint about the excessive vertical formatting of `google-java-format`.

The only actual code change here is the configuration in `pom.xml`. The rest is the result of running the formater. The changes are easier to see if you view the diff with "hide whitespace".

This uses `<style>AOSP</style>` which maintains the 100 character limit. This change brings the option of using  `<style>PALANTIR</style>` which has a 120 character limit.

### CODE REVIEW

**Review by bhelx — APPROVED** [review]
I'm okay with this. I don't have a strong opinion on any particular format. My main concern is only that one be in place and be enforced. I typically don't like these changes because they create a lot of noise, though this one doesn't have a huge surface area so it's acceptable. The only thing I'd ask is that this is the last time we change it 😆

**Review by andreaTP — APPROVED** [review]
Fully aligned with what @bhelx said, no strong preference here.
Ideally this PR should have 2 commits, one with only the `pom.xml` changes and one applying it, but it's a nitpick, no action required.

**Comment by electrum** [comment]
@andreaTP Good point about two commits -- updated for that

**Review by danielperano — APPROVED** [review]

**Comment by danielperano** [comment]
I like it!

**Review by thomasdarimont — APPROVED** [review]

**Comment by bhelx** [comment]
Closing as discussed until we find a replacement for the Palantir formatter.

**Pull request closed without merging**
