### PR TITLE
Do not use `java.util.Stack`

### PR DESCRIPTION
**Pull request by dmlloyd**
It uses synchronization, which is rarely desirable. Use `ArrayDeque` instead.

### CODE REVIEW

**Review by andreaTP — APPROVED** [review]
Lgtm thanks for the improvement!
This looks like something that would improve performance, have you done any, even rough, benchmarks?

**Comment by dmlloyd** [comment]
No, I haven't benchmarked this particular change in any place I've made it since I convinced myself it is always worthwhile, over 15 years ago :)

**Comment by andreaTP** [comment]
Haha I fully trust you on this one!
Thanks for the change!
Lgtm

**Review by andreaTP — APPROVED** [review]

**Comment by bhelx** [comment]
> It uses synchronization

I didn't know that. we definitely don't need synchronization here

**Pull request merged**
