### PR TITLE
Remove function-annotations from the BOM

### PR DESCRIPTION
**Pull request by andreaTP**
We need to work a bit more on the annotation processing story, I noticed that we have this in the BOM and I think that we should leave it out to avoid setting wrong expectations when we release the next version.

### CODE REVIEW

**Comment by electrum** [comment]
These are already used by WASI successfully for implementing host functions. Shouldn’t we make it easy for people to try out to get more feedback?

**Comment by electrum** [comment]
Maybe best to discuss this in the meeting next week?

**Comment by andreaTP** [comment]
> Maybe best to discuss this in the meeting next week?

I might be missing this one, the idea behind this removal was to release those annotations as experimental for the 1.0 release.
I have no problem in closing this PR when we have a better defined "release plan" though, it's mostly a call to "let's think about this" than anything.

**Comment by electrum** [comment]
Having it in the BOM makes it easier to use. We can still mark them as experimental. Unless we split it out into a separate project, the artifact would still be versioned as `1.0`, so I don't see how removing it from the BOM changes anything, other than making it more difficult to use.

**Comment by andreaTP** [comment]
They'd likely be renamed etc., but your reasoning is fine for me, we have to decide how to mark experimental modules though ...

**Pull request closed without merging**
