### PR TITLE
WIP - initial docs

### PR DESCRIPTION
**Pull request by andreaTP**
Opening this just for visibility, I started scaffolding a project doc site.

If anyone want to take over or have other preferences regarding the technology(I started with Docusaurus) I'm happy to listen to feedback.

### CODE REVIEW

**Comment by bhelx** [comment]
@andreaTP Is this in a mergable state? it's okay if it's not accurate or finished yet. It just needs to properly build. Once we get it into main i can setup the cloudflare pages integration and connect the domain.

**Comment by bhelx** [comment]
We could also get it working by pushing it into a branch in this repo (out of the fork)

**Comment by andreaTP** [comment]
@bhelx this is a very very initial scaffolding.
It builds but has almost nothing in it.

Feel free to take over in any way it's more convenient to you(merging, closing and opening another, whatever).

The only requirement I would ask for is that it will be maintained on `main` (or somehow directly connected to it), I want to either integrate snippets of code(e.g. from the tests) or check that the docs are up to date automatically (like we are doing now with jbang).

**Comment by bhelx** [comment]
Closing with https://github.com/dylibso/chicory/pull/554

**Pull request closed without merging**
