### PR TITLE
Implement WASI path_readlink

### PR DESCRIPTION
**Pull request by electrum**
Python requires this when running `python foo.py`

### CODE REVIEW

**Comment by andreaTP** [comment]
The typo should be fixed on `main`.

**Review by andreaTP — APPROVED** [review]
I'm not super happy that there are no tests for this, would it be possible to enable something like: `tests/rust/testsuite/path_link.wasm` ? and maybe share some code path?
Alternatively, is it complex to do a test in isolation to cover the "happy path"?

Not going to oppose to merge though, as it looks a straight improvement anyhow, thanks.

**Comment by electrum** [comment]
It has a test in `WasiPreview1Test`. We can't run `path_link.rs` because requires `path_link`. I'm hesitant to implement that as symlinks are currently a security hole if using the normal file system.

**Comment by andreaTP** [comment]
> It has a test 

Right, I thought from the `wasi-testsuite`, but that's good enough :+1:  thanks!

**Pull request merged**
