### PR TITLE
More initial docs

### PR DESCRIPTION
**Pull request by andreaTP**
Here:

- a little more structure
- started porting a couple of section of the Readme (with `jbang` checks etc.)
- ported the initial Blog we wrote for Java Advent

Next:

- more structure
- a more scalable way to test the docs
- port the rest of the Readme

### CODE REVIEW

**Comment by bhelx** [comment]
Going to see why cloudflare didn't build this preview branch. I suspect because because this is a fork.

**Review by bhelx — APPROVED** [review]

**Comment by andreaTP** [comment]
Probably the preview doesn't work on PRs from forks.
I think you can trust me this time as it's really an in progress work, I'll push to the main repo next time.

**Comment by andreaTP** [comment]
I don't see the site being updated after the merge, @bhelx I think I need your intervention here 🙏

**Comment by bhelx** [comment]
Seems that the build failed because some updates to yarn.lock weren't checked in. will see if i can fix:

```
<pre class="c_np c_bv c_mo c_mp c_hp c_hq c_dd c_qv c_qw c_qx c_qy c_gp c_gq c_qj c_bx c_qz">
15:55:49.937 | ➤ YN0000: └ Completed in 0s 241ms
-- | --
15:55:50.000 | ➤ YN0000: ┌ Post-resolution validation
15:55:50.000 | ➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
15:55:50.000 | ➤ YN0000: └ Completed
15:55:50.000 | ➤ YN0000: Failed with errors in 0s 313ms
15:55:50.021 | Error: Exit with error code: 1
15:55:50.021 | at ChildProcess.<anonymous> (/snapshot/dist/run-build.js)
15:55:50.022 | at Object.onceWrapper (node:events:652:26)
15:55:50.022 | at ChildProcess.emit (node:events:537:28)
15:55:50.022 | at ChildProcess._handle.onexit (node:internal/child_process:291:12)
15:55:50.030 | Failed: build command exited with code: 1
15:55:51.490 | Failed: error occurred while running build command


```

**Comment by bhelx** [comment]
I had to delete `yarn.lock`. should be deployed and working again.

**Comment by andreaTP** [comment]
Looks good! Thanks for looking into this quickly and sorry for the noise.
We should put `yarn.lock` in the .gitignore file, I'll follow up tomorrow.

**Pull request merged**
