### PR TITLE
Separate non-Maven-specific code in OpCodeGen into a separate file

### PR DESCRIPTION
**Pull request by jmillikin**
Fixes https://github.com/dylibso/chicory/issues/513

### CODE REVIEW

**Comment by jmillikin** [comment]
Note: I don't have a working Maven installation on this machine, so I've verified `OpCodeGen.java` does build and work but haven't verified `OpCodeGenMojo.java`.

**Comment by andreaTP** [comment]
> Note: I don't have a working Maven installation on this machine, so I've verified OpCodeGen.java does build and work but haven't verified OpCodeGenMojo.java.

To make changes to this project you really need Maven working, what can I do to help?
Would a Maven Wrapper work for you?

**Comment by jmillikin** [comment]
Regarding Maven, I just need to set it up in a container or something and skim the tutorial so I can remember the basics. It's been years since the last time I've used it.

For contributing to Chicory itself (not just using it as a dependency), I would definitely be sure to use Maven for the build + tests so I can be sure my local development is matching upstream standard.

**Comment by andreaTP** [comment]
Superseded by #515

**Pull request closed without merging**
