### PR TITLE
Improve immutability of the data structure of the wasm module

### PR DESCRIPTION
**Pull request by andreaTP**
Opening in draft as I expect this PR to have impacts on performance.

@electrum would you like to propose improvements on top of this?

### CODE REVIEW

**Review by electrum — APPROVED** [review]

**Comment by andreaTP** [comment]
@electrum now that we merged #517 should we close this one?
From your comments, looks like we only miss a couple of defensive copies of Lists, correct?

**Comment by electrum** [comment]
I think most of these changes are separate from #517.

**Comment by andreaTP** [comment]
Cool :+1: thanks for reviewing!

**Comment by electrum** [comment]
What I meant is that we still need this PR, as most of the changes here are different from the ones in #517.

**Comment by andreaTP** [comment]
Ouch, ok, I'll keep it on the Todo list.

**Pull request closed without merging**
