### PR TITLE
imports.wast tests infrastructure and global imports support

### PR DESCRIPTION
**Pull request by andreaTP**
Looking for feedback on this approach to testing imported functions/things.

I was thinking about generating the `HostFunctions`, but I'm unsure how this will play out ... probably defining them explicitly is going to be more flexible, thoughts?

### CODE REVIEW

**Comment by bhelx** [comment]
> I was thinking about generating the HostFunctions, but I'm unsure how this will play out ... probably defining them explicitly is going to be more flexible, thoughts?

I think if we can get away with a static set of hand written host function then we should do that. I haven't looked too closely, but i think the imports with different behaviors different names so this should work.

**Comment by andreaTP** [comment]
Thanks for the feedback @bhelx I'll continue in this direction 👍

**Comment by andreaTP** [comment]
A few bits are a bit hacked around, feel free to ask for changes or improvements.

This PR features:
- Test Gen Maven Plugin support for the `imports.wast` spec
- Implement Global Imports

I think this is already big enough to review, we can follow up with Memory and Table imports in a follow-up PR.

**Comment by andreaTP** [comment]
@bhelx heads up, this is ready for review.

**Review by bhelx — APPROVED** [review]
This is a pretty sprawling change so I think it's worth merging now and following up on small stuff and remaining specs. Thanks!

**Pull request merged**
